### ISSUE TITLE
Just a notice even though this is just for demo

### ISSUE THREAD

**Issue by kris9854** [shadowman-lab/Ansible-ImageBuilder#2]
I know this is a demo repo but just FYI 
```yaml
  - name: Copy Key
    ansible.builtin.copy:
      src: "{{ keysourcelocation }}"
      dest: /etc/pki/tls/private/localhost.key
      owner: root
      group: root
      mode: '0644'
```

Should be:

```yaml
  - name: Copy Key
    ansible.builtin.copy:
      src: "{{ keysourcelocation }}"
      dest: /etc/pki/tls/private/localhost.key
      owner: root
      group: root
      mode: '0600'
```

As the .key shouldn't be readable for everyone on the server :)

Hope it is okay to give this
